package cl.gus.labs.fakestore.convention

import java.io.DataInputStream
import java.io.File

/**
 * Renders `docs/ui-gallery.md`: one table per screenshot folder, light and dark side by side.
 * Previews come first; the edge cases written by hand as plain tests follow.
 */
internal fun renderUiGallery(root: File, baselines: Set<File>): String = buildString {
    append(HEADER)

    val folders = baselines.groupBy { it.parentFile }
    val (designSystem, screens) = folders.keys
        .sortedBy { it.relativeTo(root).invariantSeparatorsPath }
        .partition { it.parentFile.relativeTo(root).invariantSeparatorsPath == DESIGN_SYSTEM_SCREENSHOTS }

    designSystem
        .sortedBy { LAYER_TITLES.keys.indexOf(it.name).let { index -> if (index < 0) Int.MAX_VALUE else index } }
        .forEach { folder ->
            append("\n## ${LAYER_TITLES[folder.name] ?: folder.title}\n\n")
            appendTables(root, folders.getValue(folder), DESIGN_SYSTEM_SCALE_PERCENT)
        }

    append("\n## Screens\n")
    screens.forEach { folder ->
        append("\n### ${folder.title}\n\n")
        appendTables(root, folders.getValue(folder), SCREEN_SCALE_PERCENT)
    }
}

private fun StringBuilder.appendTables(root: File, images: List<File>, scalePercent: Int) {
    val shots = images.groupBy { it.nameWithoutExtension.replace(THEME_SUFFIX, "") }.toSortedMap()
    val (previews, tests) = shots.keys.partition { it.startsWith(PREVIEW_PREFIX) }

    fun table(header: String, stems: List<String>) {
        append("| $header | Light | Dark |\n|---|---|---|\n")
        stems.forEach { stem ->
            val files = shots.getValue(stem)
            val name = stem.removePrefix(PREVIEW_PREFIX)
            val light = files.find { it.name == "${stem}_Light.png" } ?: files.find { it.name == "$stem.png" }
            val dark = files.find { it.name == "${stem}_Dark.png" }
            append("| ${label(stem, name)} | ${image(root, light, "$name, light", scalePercent)} ")
            append("| ${image(root, dark, "$name, dark", scalePercent)} |\n")
        }
    }

    if (previews.isNotEmpty()) table("Preview", previews)
    if (tests.isNotEmpty()) {
        append("\n**Edge cases**, from tests written by hand:\n\n")
        table("Test", tests)
    }
}

// `CatalogScreenEmpty` reads as the screen and its state.
private fun label(stem: String, name: String): String {
    val screen = SCREEN_AND_STATE.matchEntire(name)
    return if (stem.startsWith(PREVIEW_PREFIX) && screen != null) {
        "`${screen.groupValues[1]}` · ${screen.groupValues[2]}"
    } else {
        "`$name`"
    }
}

// One scale per table keeps the images comparable in size.
private fun image(root: File, file: File?, alt: String, scalePercent: Int): String {
    if (file == null) return "—"
    val width = file.pngWidth() * scalePercent / 100
    return """<img src="../${file.relativeTo(root).invariantSeparatorsPath}" width="$width" alt="$alt">"""
}

// The IHDR chunk starts at byte 16 with the width.
private fun File.pngWidth(): Int = DataInputStream(inputStream()).use { it.skipBytes(16); it.readInt() }

private val File.title: String get() = name.replaceFirstChar { it.uppercase() }

private const val DESIGN_SYSTEM_SCREENSHOTS = "core/designsystem/src/test/screenshots"
private const val PREVIEW_PREFIX = "Preview"
private const val DESIGN_SYSTEM_SCALE_PERCENT = 40
private const val SCREEN_SCALE_PERCENT = 25
private val THEME_SUFFIX = Regex("_(Light|Dark)$")
private val SCREEN_AND_STATE = Regex("^(.+Screen)(.+)$")
private val LAYER_TITLES = linkedMapOf(
    "preview" to "Foundations",
    "atom" to "Atoms",
    "molecule" to "Molecules",
    "organism" to "Organisms",
)

private val HEADER = """
    # UI gallery

    <!-- Generated by ./gradlew uiGallery from the screenshot baselines. Do not edit by hand. -->

    Every design-system preview and screen, as the screenshot tests render it. The build verifies each
    image and fails when this page misses one, so it shows what the code draws today. The
    [design system](design-system.md) explains the layers; [testing](testing.md#screenshots) how the
    images are recorded.

""".trimIndent()
